<!-- Copyright (C) 2009 Google Inc.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: Shaopeng Jia

     MetaData on Phone Number Plan and formatting rules
     Note: Territories are in alphabetical order by their IDs, which are
           based on ISO 3166-1 two-letter country codes. The country names
           in the comments are the official short names in English according
           to ISO 3166-1.

     For more information on what each element represents, see
     java/com/google/i18n/phonenumbers/phonemetadata.proto

     Note that if you want to add validation metadata, the generalDesc
     nationalNumberPattern and possibleNumberPattern must be provided.
     If this is missing, then the country will be considered to have no more
     specific phone-number type metadata (fixedLine, mobile etc) and hence only
     basic validation rules (numbers should be between 3 and 15 digits long)
     will be applied.
-->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (availableFormats?, generalDesc?, fixedLine?, mobile?, tollFree?,
        premiumRate?, sharedCost?, personalNumber?, voip?)>
    <!ELEMENT generalDesc (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT fixedLine (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT mobile (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT tollFree (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT premiumRate (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT sharedCost (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT personalNumber (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voip (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT availableFormats (numberFormat+, intlNumberFormat*)>
    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT possibleNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT numberFormat (#PCDATA)>
    <!ELEMENT intlNumberFormat (#PCDATA)>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory preferredInternationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory internationalPrefix CDATA #REQUIRED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixForParsing CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixTransformRule CDATA #IMPLIED>
    <!ATTLIST territory preferredExtnPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat leadingDigits CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
    <!ATTLIST intlNumberFormat leadingDigits CDATA #IMPLIED>
    <!ATTLIST intlNumberFormat pattern CDATA #REQUIRED>
    ]>

<phoneNumberMetadata>
  <territories>
    <!-- Andorra -->
    <!-- http://www.itu.int/oth/T0202000005/en -->
    <territory id="AD" countryCode="376" internationalPrefix="00">
      <availableFormats>
        <numberFormat leadingDigits="[346-9]" pattern="(\d{3})(\d{3})">$1 $2</numberFormat>
        <numberFormat leadingDigits="1" pattern="(180[02])(\d{4})">$1 $2</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>(?:[346-9]|180)\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6,8}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>[78]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>712345</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>[346]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>312345</exampleNumber>
      </mobile>
      <tollFree>
        <!-- Note that the definitions of 1800 and 1802 numbers differ in the
        plan and on the Andorran www.sta.ad website, but we consider both to be
        freephone here. -->
        <nationalNumberPattern>180[02]\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{8}</possibleNumberPattern>
        <exampleNumber>18001234</exampleNumber>
      </tollFree>
      <!-- The national numbering plan says that numbers beginning with 9 are
      reserved for special services, so we assume they are premium rate here,
      although we cannot find examples online.-->
      <premiumRate>
        <nationalNumberPattern>9\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>912345</exampleNumber>
      </premiumRate>
    </territory>

    <!--  United Arab Emirates -->
    <!-- http://www.itu.int/oth/T02020000DC/en -->
    <territory id="AE" countryCode="971" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat leadingDigits="[2-4679][2-8]"
                      pattern="([2-4679])(\d{3})(\d{4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="5" pattern="(5[056])(\d{3})(\d{4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="[4679]0"
                      pattern="([4679]00)(\d)(\d{5})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="8" pattern="(800)(\d{2})(\d{0,7})">$1 $2 $3</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[2-79]\d{7,8}|800\d{2,9}</nationalNumberPattern>
        <possibleNumberPattern>\d{5,12}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>(?:[2-4679][2-8]\d|600[25])\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{7,9}</possibleNumberPattern>
        <exampleNumber>22345678</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>5[056]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>501234567</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>400\d{6}|800\d{2,9}</nationalNumberPattern>
        <possibleNumberPattern>\d{5,12}</possibleNumberPattern>
        <exampleNumber>800123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[02]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>900234567</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>700[05]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>700012345</exampleNumber>
      </sharedCost>
    </territory>

    <!-- Afghanistan -->
    <!-- http://www.itu.int/oth/T0202000001/en -->
    <territory id="AF" countryCode="93" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat pattern="([2-7]\d)(\d{3})(\d{4})">$1 $2 $3</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[2-7]\d{8}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>(?:[25][0-8]|[34][0-4]|6[0-5])[2-9]\d{6}</nationalNumberPattern>
        <exampleNumber>234567890</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>7[057-9]\d{7}</nationalNumberPattern>
        <exampleNumber>701234567</exampleNumber>
      </mobile>
    </territory>

    <!-- Antigua and Barbuda -->
    <!-- http://www.itu.int/oth/T0202000008/en -->
    <territory id="AG" countryCode="1" internationalPrefix="011">
      <generalDesc>
        <!-- NANPA country - uses US formatting rules -->
        <nationalNumberPattern>[289]\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{7,10}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>268(?:4(?:6[0-3]|84)|56[0-2])\d{4}</nationalNumberPattern>
        <exampleNumber>2684601234</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>268(?:464|7(?:2[0-9]|64|7[0-5]|8[358]))\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2684641234</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>8(?:00|66|77|88)[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>8002123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>9002123456</exampleNumber>
      </premiumRate>
      <voip>
        <!-- This is included as Centrex in the plan.-->
        <nationalNumberPattern>26848[01]\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2684801234</exampleNumber>
      </voip>
    </territory>

    <!-- Anguilla -->
    <!-- http://www.itu.int/oth/T0202000007/en -->
    <territory id="AI" countryCode="1" internationalPrefix="011">
      <generalDesc>
        <!-- NANPA country - uses US formatting rules -->
        <nationalNumberPattern>[289]\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{7,10}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>2644(?:6[12]|9[78])\d{4}</nationalNumberPattern>
        <exampleNumber>2644612345</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>264(?:235|476|5(?:3[6-9]|8[1-4])|7(?:29|72))\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2642351234</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>8(?:00|66|77|88)[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>8002123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>9002123456</exampleNumber>
      </premiumRate>
    </territory>

    <!-- Albania -->
    <!-- http://www.itu.int/oth/T0202000002/en -->
    <territory id="AL" countryCode="355" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <!-- Formats mostly follow http://tirana.usembassy.gov/list_of_doctors.html -->
        <numberFormat leadingDigits="4[0-6]"
                      pattern="(4)(\d{3})(\d{4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="6"
                      pattern="(6[6-9])(\d{3})(\d{4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="[2358][2-5]|4[7-9]"
                      pattern="(\d{2})(\d{3})(\d{3})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="[2358][16-9]"
                      pattern="(\d{3})(\d{5})">$1 $2</numberFormat>
        <numberFormat leadingDigits="800" pattern="(800)(\d{4})">$1 $2</numberFormat>
        <numberFormat leadingDigits="9|808" pattern="(\d{3})(\d{3})">$1 $2</numberFormat>
        <numberFormat leadingDigits="7" pattern="(700)(\d{5})">$1 $2</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[2-57]\d{7}|6\d{8}|8\d{5,7}|9\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{5,9}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>(?:2(?:[168][1-9]|[247]\d|9[1-7])|3(?:1[1-3]|[2-6]\d|[79][1-8]|8[1-9])|4\d{2}|5(?:1[1-4]|[2-578]\d|6[1-5]|9[1-7])|8(?:[19][1-5]|[2-6]\d|[78][1-7]))\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{5,8}</possibleNumberPattern>
        <exampleNumber>22345678</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>6[6-9]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>661234567</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>800\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{7}</possibleNumberPattern>
        <exampleNumber>8001234</exampleNumber>
      </tollFree>
      <premiumRate>
        <!-- It is named "Shared Revenue Services" in the plan, but as there is a separate "Shared
             Cost Services", it is highly likely these numbers are premium rate numbers. No
             information/example is found in the Internet. -->
        <nationalNumberPattern>900\d{3}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>900123</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>808\d{3}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>808123</exampleNumber>
      </sharedCost>
      <personalNumber>
        <nationalNumberPattern>700\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{8}</possibleNumberPattern>
        <exampleNumber>70012345</exampleNumber>
      </personalNumber>
    </territory>

    <!-- Armenia -->
    <territory id="AM" countryCode="374" internationalPrefix="00"
               nationalPrefix="8">
    </territory>

    <!-- Netherlands Antilles -->
    <territory id="AN" countryCode="599" internationalPrefix="00">
    </territory>

    <!-- Angola -->
    <!-- http://www.itu.int/oth/T0202000006/en -->
    <territory id="AO" countryCode="244" internationalPrefix="00">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{3})(\d{3})">$1 $2 $3</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[29]\d{8}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>2\d(?:[26-9]\d|\d[26-9])\d{5}</nationalNumberPattern>
        <exampleNumber>222123456</exampleNumber>
      </fixedLine>
      <mobile>
        <!-- Expanded the 92 prefix possibilities to matchnumbers found online. -->
        <nationalNumberPattern>9[1-3]\d{7}</nationalNumberPattern>
        <exampleNumber>923123456</exampleNumber>
      </mobile>
    </territory>

    <!-- Argentina -->
    <!-- http://www.itu.int/oth/T0202000009/en -->
    <!-- http://www.cnc.gov.ar/numeracion/IndicativosInterurbanos.asp -->
    <territory id="AR" countryCode="54" internationalPrefix="00"
               nationalPrefix="0"  nationalPrefixForParsing="0(?:(11|2(?:2(?:02?|[13]|2[13-79]|4[1-6]|5[2457]|6[124-8]|7[1-4]|8[13-6]|9[1-367])|3(?:[06]2|1[467]|2[02-6]|3[13-8]|[49][2-6]|5[2-8]|7)|47[3-578]|6(?:1|2[2-7]|4[6-8]?|5[125-8])|9(?:0[1-3]|[19]|2\d|3[1-6]|4[0-24-68]|5[2-4]|6[2-6]|72?|8[23]?))|3(?:3(?:2[79]|8[2578])|4(?:0[124-9]|[12]|3[5-8]?|4[24-7]|5[4-68]?|6\d|7[126]|8[237-9]|9[1-36-8])|5(?:1|2[1245]|3[2-4]?|4[1-46-9]|6[2-4]|7[1-6]|8[2-5]?)|7(?:1[15-8]|2[125]|3[1245]|4[13]|5[124-8]|7[2-57]|8[1-36])|8(?:1|2[125-7]|3[23578]|4[13-6]|5[4-8]?|6[1-357-9]|7[5-8]?|8[4-7]?|9[124])))15)?"
               nationalPrefixTransformRule="9$1" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat leadingDigits="[68]"
                      pattern="([68]\d{2})(\d{3})(\d{4})">$1-$2-$3</numberFormat>
        <intlNumberFormat leadingDigits="[68]"
                          pattern="([68]\d{2})(\d{3})(\d{4})">$1-$2-$3</intlNumberFormat>
        <numberFormat leadingDigits="91" pattern="9(11)(\d{4})(\d{4})">$1 15-$2-$3</numberFormat>
        <intlNumberFormat leadingDigits="91"
                          pattern="9(11)(\d{4})(\d{4})">9 $1 $2-$3</intlNumberFormat>
        <numberFormat leadingDigits="9(?:2(?:2[013]|37|6[14]|9[179])|3(?:4[1235]|5[138]|8[1578]))"
                      pattern="9(\d{3})(\d{3})(\d{4})">$1 15-$2-$3</numberFormat>
        <intlNumberFormat
            leadingDigits="9(?:2(?:2[013]|37|6[14]|9[179])|3(?:4[1235]|5[138]|8[1578]))"
            pattern="9(\d{3})(\d{3})(\d{4})">9 $1 $2-$3</intlNumberFormat>
        <numberFormat
            leadingDigits="9(?:2(?:2[24-9]|3[0-69]|47|6[25]|9[02-68])|3(?:3[28]|4[046-9]|5[2467]|7[1-578]|8[23469]))"
            pattern="9(\d{4})(\d{2})(\d{4})">$1 15-$2-$3</numberFormat>
        <intlNumberFormat
            leadingDigits="9(?:2(?:2[24-9]|3[0-69]|47|6[25]|9[02-68])|3(?:3[28]|4[046-9]|5[2467]|7[1-578]|8[23469]))"
            pattern="9(\d{4})(\d{2})(\d{4})">9 $1 $2-$3</intlNumberFormat>
        <numberFormat leadingDigits="1" pattern="(11)(\d{4})(\d{4})">$1 $2-$3</numberFormat>
        <intlNumberFormat leadingDigits="1"
                          pattern="(11)(\d{4})(\d{4})">$1 $2-$3</intlNumberFormat>
        <!-- Some 4-digit area codes actually are caught by this
             rule. I'm giving however preference to the 3-digit area
             codes, since they are considerably larger
             communities. -->
        <numberFormat leadingDigits="2(?:2[013]|37|6[14]|9[179])|3(?:4[1235]|5[138]|8[1578])"
                      pattern="(\d{3})(\d{3})(\d{4})">$1 $2-$3</numberFormat>
        <intlNumberFormat leadingDigits="2(?:2[013]|37|6[14]|9[179])|3(?:4[1235]|5[138]|8[1578])"
                          pattern="(\d{3})(\d{3})(\d{4})">$1 $2-$3</intlNumberFormat>
        <numberFormat leadingDigits="[23]" pattern="(\d{4})(\d{2})(\d{4})">$1 $2-$3</numberFormat>
        <intlNumberFormat leadingDigits="[23]"
                          pattern="(\d{4})(\d{2})(\d{4})">$1 $2-$3</intlNumberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[1-9]\d{9,11}</nationalNumberPattern>
        <possibleNumberPattern>\d{6,12}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>[1-9]\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{6,10}</possibleNumberPattern>
        <exampleNumber>1123456789</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>9(?:11[2-9]\d{7}|(?:2(?:2[013]|37|6[14]|9[179])|3(?:4[1235]|5[138]|8[1578]))[2-9]\d{6}|\d{4}[2-9]\d{5})</nationalNumberPattern>
        <possibleNumberPattern>\d{6,12}</possibleNumberPattern>
        <exampleNumber>91123456789</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>80\d{8}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>8012345678</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>6(?:0\d|10)\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>6001234567</exampleNumber>
      </premiumRate>
    </territory>

    <!-- American Samoa -->
    <!-- http://www.itu.int/oth/T0202000004/en -->
    <territory id="AS" countryCode="1" internationalPrefix="011">
      <generalDesc>
        <!-- NANPA country - uses US formatting rules -->
        <nationalNumberPattern>[689]\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{7,10}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>6846(?:22|33|44|55|77|88|9[19])\d{4}</nationalNumberPattern>
        <exampleNumber>6846221234</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>684(?:733|258)\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>6847331234</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>8(?:00|66|77|88)[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>8002123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>9002123456</exampleNumber>
      </premiumRate>
    </territory>

    <!-- Austria -->
    <!-- http://www.rtr.at/en/tk/E129 -->
    <territory id="AT" countryCode="43" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat leadingDigits="1|5[079]" pattern="([15])(\d{3,12})">$1 $2</numberFormat>
        <numberFormat leadingDigits="316|46|51|732|6(?:44|5[0-3579]|[6-9])|7(?:1|[28]0)|[89]"
                      pattern="(\d{3})(\d{3,10})">$1 $2</numberFormat>
        <numberFormat
            leadingDigits="2|3(?:1[1-578]|[3-8])|4[2378]|5[2-6]|6(?:[12]|4[1-35-9]|5[468])|7(?:2[1-8]|35|4[1-8]|[57-9])"
            pattern="(\d{4})(\d{3,9})">$1 $2</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>\d{4,13}</nationalNumberPattern>
        <possibleNumberPattern>\d{3,13}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <!-- Note the 050, 057 and 059 prefixes are defined as "private network"
        in the Austrian plan. This just means they are registered to companies
        who are distributed over different geographical areas and maintain their
        own network. Examples here: http://www.rtr.at/?id=4506&S=05&art=d Also
        note that the full area code is not validated - just the first 3 digits.
        This also means that even though for most Austrian numbers the minimum
        length is 7, we allow 6 since we don't differentiate below between 3 and
        4 digit area codes for reasons of efficiency.
        -->
        <nationalNumberPattern>1\d{3,12}|(?:2(?:1[467]|2[134-8]|5[2357]|6[1-46-8]|7[1-8]|8[124-7]|8[1458])|3(?:1[1-8]|3[23568]|4[5-7]|5[1378]|6[1-38]|8[3-68])|4(?:2[1-8]|35|63|7[1368]|8[2457])|5(?:1[27]|2[1-8]|3[357]|4[147]|5[12578]|6[37])|6(?:13|2[1-47]|4[1-35-8]|5[468]|62)|7(?:2[1-8]|3[25]|4[13478]|5[68]|6[16-8]|7[1-6]|9[45]))\d{3,10}|5(?:0[1-9]|[79]\d)\d{2,10}|720\d{6,10}</nationalNumberPattern>
        <exampleNumber>1234567890</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>6(?:44|5[0-3579]|6[013-9]|[7-9]\d)\d{4,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{7,13}</possibleNumberPattern>
        <exampleNumber>644123456</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>80[02]\d{6,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>800123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>(?:711|9(?:0[01]|3[019]))\d{6,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>900123456</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>8(?:10|2[018])\d{6,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>810123456</exampleNumber>
      </sharedCost>
      <voip>
        <nationalNumberPattern>780\d{6,10}</nationalNumberPattern>
        <possibleNumberPattern>\d{9,13}</possibleNumberPattern>
        <exampleNumber>780123456</exampleNumber>
      </voip>
    </territory>

    <!-- Australia -->
    <!-- http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200000D0001MSWE.doc -->
    <!-- http://en.wikipedia.org/wiki/Telephone_numbers_in_Australia -->
    <territory id="AU" countryCode="61" preferredInternationalPrefix="0011"
               internationalPrefix="(?:14(?:1[14]|34|4[17]|[56]6|7[47]|88))?001[14-689]"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat leadingDigits="[2378]"
                      pattern="([2378])(\d{4})(\d{4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="4" pattern="(4\d{2})(\d{3})(\d{3})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="5"
                      pattern="(5[05]0)(\d{3})(\d{3})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="1(?:[38]00|9)" nationalPrefixFormattingRule="$FG"
                      pattern="(1[389]\d{2})(\d{3})(\d{3})">$1 $2 $3</numberFormat>
        <!-- Although the national plan doesn't explicitly say so, there is no evidence that a
             180 xxxx number could be 180 0xxx. -->
        <numberFormat leadingDigits="180[1-9]" nationalPrefixFormattingRule="$FG"
                      pattern="(180)(\d{4})">$1 $2</numberFormat>
        <numberFormat leadingDigits="13[1-9]" nationalPrefixFormattingRule="$FG"
                      pattern="(13)(\d{2})(\d{2})">$1 $2 $3</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[1-578]\d{5,9}</nationalNumberPattern>
        <possibleNumberPattern>\d{6,10}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>[2378]\d{8}</nationalNumberPattern>
        <possibleNumberPattern>\d{8,9}</possibleNumberPattern>
        <exampleNumber>212345678</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>4[0-68]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>412345678</exampleNumber>
      </mobile>
      <tollFree>
        <!-- Local-rate (SmartNumbers) are put here for now because they are
             also a reverse-charge network, although they charge a small local call
             connect fee (around 25c). These start with 13 or 1300. -->
        <nationalNumberPattern>1(?:80(?:0\d{2})?|3(?:00\d{2})?)\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{6,10}</possibleNumberPattern>
        <exampleNumber>1800123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>190[0126]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>1900123456</exampleNumber>
      </premiumRate>
      <!-- Wikipedia was the source for these types of numbers, and number
      allocation search here
      http://web.acma.gov.au/numb/openAccess/inquiry/allocationSearch.do
      confirms this. (Search from 0500000000 to 0590000000)-->
      <personalNumber>
        <nationalNumberPattern>500\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>500123456</exampleNumber>
      </personalNumber>
      <voip>
        <nationalNumberPattern>550\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>550123456</exampleNumber>
      </voip>
    </territory>

    <!-- Aruba -->
    <!-- http://www.itu.int/oth/T020200000B/en -->
    <territory id="AW" countryCode="297" internationalPrefix="00">
      <availableFormats>
        <numberFormat pattern="([57-9]\d{2})(\d{4})">$1 $2</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[57-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{7}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>5(?:2\d{2}|8(?:[2-7]\d|8[0-79]|9[48]))\d{3}</nationalNumberPattern>
        <exampleNumber>5212345</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>(?:5[69]\d|9(?:6\d|9[02-9])|7[34]\d)\d{4}</nationalNumberPattern>
        <exampleNumber>5601234</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>800\d{4}</nationalNumberPattern>
        <exampleNumber>8001234</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900\d{4}</nationalNumberPattern>
        <exampleNumber>9001234</exampleNumber>
      </premiumRate>
    </territory>

    <!-- Azerbaijan -->
    <!-- http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200000F0001MSWE.doc -->
    <territory id="AZ" countryCode="994" internationalPrefix="00">
      <availableFormats>
        <numberFormat leadingDigits="[4-8]"
                      pattern="([4-8]\d)(\d{3})(\d{4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="1[28]|22"
                      pattern="([12]\d)(\d{3})(\d{3,4})">$1 $2 $3</numberFormat>
        <numberFormat leadingDigits="1[013-79]|2[013-9]"
                      pattern="([12]\d{2})(\d{5})">$1 $2</numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[124-8]\d{7,8}</nationalNumberPattern>
        <possibleNumberPattern>\d{8,9}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>(?:1(?:(?:[28]\d|36|9)\d|02|1[0-589]|3[358]|4[013-79]|5[0-479]|6[0236-9]|7[0-24-8])|2(?:16|2\d|3[0-24]|4[1468]|55|6[56]|79))\d{5}</nationalNumberPattern>
        <exampleNumber>123123456</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>(?:4[04]|5[015]|60|7[07])\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>401234567</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>88\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>881234567</exampleNumber>